version: '3'
services:
  app:
    container_name: doctrack-app
    image: betoooo/doctrack:v1.0.0 
    restart: unless-stopped
    ports:
      - "8081:8081" 
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache  
    environment:
      - APP_NAME=DocTrack
      - APP_ENV=local
      - APP_KEY=base64:HN3HX+lGSS6xFiq7c+wxZMsOVdFgyXn3hGur/sH3GPg=
      - APP_DEBUG=false
      - APP_URL=http://192.168.1.179
      - DB_CONNECTION=pgsql
      - DB_HOST=192.168.1.35  
      - DB_PORT=5432
      - DB_DATABASE=internal_tracking_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=MDA_TecInfo@2024
      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=file
      - FILESYSTEM_DISK=local
      - QUEUE_CONNECTION=sync
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
    networks:
      - doctrack-network

networks:
  doctrack-network:
    driver: bridge